### ISSUE TITLE
Parallelized recording (via command line)

### ISSUE THREAD

**Issue by nyanpasu64** [nyanpasu64/vgmsplit#2]
nuked is VERY slow (10 minutes) to record all channels. mame is 1 minute, which is still inconvenient.

There should be a CLI option `--channels 0,1,2...` to only record certain channels. Terminating individual channels while the program is running (once you find out they're silent) is nice-to-have, but easier to not bother implementing terminal input.

If we spawned worker processes instead of threads, you could use taskmgr to kill unwanted channels.

**Comment by jimbo1qaz** [comment]
Switched to MAME core, which is fast enough I don't want this anymore.

**Comment by jimbo1qaz** [comment]
doesn't take 10 minutes, but still takes 1 minute

**Comment by nyanpasu64** [comment]
openmp
